### ISSUE TITLE
Cannot access to `railsgirls.com` with HTTPS

### ISSUE THREAD

**Issue by urimaro** [railsgirls/guides.railsgirls.org#516]
Rails Girls Guide( guides.railsgirls.com ) accepts requests with HTTPS, but Rails Girls( railsgirls.com ) does not do it.
Is there any reason why we cannot deploy the server certificate?

**Comment by Djritz50** [comment]
Why

**Comment by tombruijn** [comment]
Very good point. The guides are accessible through https, but the main website is not.

This has been on my to do list for a while, but I need the help of whoever is managing the Rails Girls server and/or domain.

I want to look if we can move everything to GitHub pages (using GitHub actions), even for the periodic builds if there are any, and get https support that way. If anyone else of the team knows who manages the hosting, let me know.

**Comment by vesan** [comment]
@tombruijn Hosting is managed by @ksaa and I think the domain also. There is periodic build (once an hour if I remember correctly).

**Comment by tombruijn** [comment]
Thanks @vesan! I'll reach out out Karri in the coming days 👍

**Comment by hsbt** [comment]
I migrated railsgirls.com to https://railsgirls.org/ now. We can access railsgirls.org with HTTPS.
